name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          python main.py
      
      - name: log
        uses: actions/upload-artifact@v3
        with: 
          name: Saving logs
          path: main.log

      - name: Log in to Docker Hub
        env:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ env.password }} | docker login -u ${{ env.username }} --password-stdin

      - name: Build the docker image
        run: |
           docker build . -t alikhan0/machine-learning-ica-1:${{ github.sha}}
          
      - name: push Docker image
      env:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ env.password }} | docker login -u ${{ env.username }} --password-stdin
          docker push alikhan0/machine-learning-ica-1:${{ github.sha}}


      



